version: 2.1

commands:
  print_pipeline_id:
    description: "A very simple command for displaying the pipeline_ID "
    parameters:
      to:
        type: string
        default: ${CIRCLE_WORKFLOW_ID}
    steps:
      - run: echo << parameters.to >>


jobs:
  Qadry_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflows:
  Qadry_workflow:
    jobs:
      - Qadry_job